[project]
name = "todo-project"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
]
