"""add deadline_date to tasks

Revision ID: 47f2a66931b3
Revises: 6cff744d85f6
Create Date: 2026-08-29 20:06:11.946568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f2a66931b3'
down_revision: Union[str, Sequence[str], None] = '6cff744d85f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline_date')
    # ### end Alembic commands ###
